sudo: false
dist: trusty
cache:
  bundler: false
  directories:
    - /home/travis/.rbenv
    - /opt/pyenv/versions
env:
  - RBENV_VERSION="2.1.10"
  - RBENV_VERSION="2.2.7"
  - RBENV_VERSION="2.3.4"
  - RBENV_VERSION="2.4.2"
  - PYENV_VERSION="2.7"
  - PYENV_VERSION="2.7-dev"
  - PYENV_VERSION="3.3.6"
  - PYENV_VERSION="3.3-dev"
  - PYENV_VERSION="3.4.6"
  - PYENV_VERSION="3.4-dev"
  - PYENV_VERSION="3.5.3"
  - PYENV_VERSION="3.5-dev"
  - PYENV_VERSION="3.6.2"
  - PYENV_VERSION="3.6-dev"
  - PYENV_VERSION="3.7-dev"
install: bin/setup
script: bin/test
